/**
 * Electron host for the reverse-engineered Ajazz driver.
 *
 * Clean TypeScript rewrite of the original ../main.js. For now it serves the
 * EXISTING (already scraped + patched) UI from ../app over a local HTTP server
 * — the protocol layer in src/protocol/ is the foundation a custom UI will use
 * later, but the shipping UI stays the upstream one for now.
 *
 * Differences from the original wrapper:
 *  - TypeScript, compiled to dist/.
 *  - The served root is resolved relative to the repo so this app can live in
 *    reverse-source/ while reusing ../app.
 */
import { app, BrowserWindow } from "electron";
import type { Session } from "electron";
import * as http from "http";
import * as fs from "fs";
import * as path from "path";

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".css": "text/css",
  ".js": "text/javascript",
  ".json": "application/json",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".gif": "image/gif",
  ".ico": "image/x-icon",
  ".svg": "image/svg+xml",
};

// Resolve the UI root. In a packaged build the UI is copied next to the project
// root as `app-ui/` (sibling of dist/); in the dev tree we fall back to the
// repo-root `../../app` generated by build_offline.py.
function resolveWebRoot(): string {
  const bundled = path.join(__dirname, "..", "app-ui"); // packaged: resources/app/app-ui
  if (fs.existsSync(path.join(bundled, "index.html"))) return bundled;
  return path.resolve(__dirname, "..", "..", "app"); // dev: repo-root app/
}
const WEB_ROOT = resolveWebRoot();

let server: http.Server | undefined;

function startLocalServer(): Promise<number> {
  return new Promise((resolve) => {
    server = http.createServer((req, res) => {
      let urlPath = (req.url ?? "/").split("?")[0];
      if (urlPath === "/") urlPath = "/index.html";

      const fullPath = path.join(WEB_ROOT, urlPath);
      // Path-traversal guard: never serve outside WEB_ROOT.
      if (!fullPath.startsWith(WEB_ROOT)) {
        res.statusCode = 403;
        res.end("Forbidden");
        return;
      }

      const ext = path.extname(fullPath).toLowerCase();
      const contentType = MIME_TYPES[ext] || "application/octet-stream";

      fs.readFile(fullPath, (err, data) => {
        if (err) {
          res.statusCode = err.code === "ENOENT" ? 404 : 500;
          res.end(err.code === "ENOENT" ? "Not Found" : "Internal Server Error");
          return;
        }
        res.writeHead(200, { "Content-Type": contentType, "Access-Control-Allow-Origin": "*" });
        res.end(data);
      });
    });

    server.listen(0, "127.0.0.1", () => {
      const addr = server!.address();
      const port = typeof addr === "object" && addr ? addr.port : 0;
      console.log(`Local offline server running at http://127.0.0.1:${port}`);
      resolve(port);
    });
  });
}

function autoGrantWebHID(ses: Session): void {
  // Zero-configuration USB pairing: pick the first device, blanket-approve HID.
  ses.on("select-hid-device", (event, details, callback) => {
    event.preventDefault();
    const first = details.deviceList?.[0];
    if (first) {
      console.log("WebHID: auto-selecting device:", first.name);
      callback(first.deviceId);
    } else {
      console.log("WebHID: no HID devices found.");
      callback();
    }
  });
  ses.setPermissionCheckHandler((_wc, permission) => permission === "hid");
  ses.setDevicePermissionHandler((details) => details.deviceType === "hid");
}

function createWindow(port: number): void {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    title: "AJAZZ Local Configuration Utility (Reverse)",
    autoHideMenuBar: true,
    show: false,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: false, // required for WebHID + local caching, same as original
      zoomFactor: 0.85,
    },
  });

  autoGrantWebHID(win.webContents.session);

  win.maximize();
  win.show();
  void win.loadURL(`http://127.0.0.1:${port}/`);

  if (process.argv.includes("--devtools")) {
    win.webContents.openDevTools();
  }
}

app.whenReady().then(async () => {
  const port = await startLocalServer();
  createWindow(port);

  app.on("activate", async () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      const p = server ? (server.address() as any).port : await startLocalServer();
      createWindow(p);
    }
  });
});

app.on("window-all-closed", () => {
  server?.close();
  if (process.platform !== "darwin") app.quit();
});
