#!/usr/bin/env python3
"""Extract the keyboard model table from the layout-default chunk into models.ts.

Each model in the upstream bundle looks like:
  {vendorId:3141,productId:32774,supplierName:"ajazz",name:"AK870MC",
   connectType:"USB",routesName:["customKeys","lighting","macro","settings"],
   keyboardImg:"...png", ...}

Re-run after an upstream rebuild (the layout-default hash changes each time).
"""
import glob
import json
import re

LD = sorted(glob.glob("../app/assets/layout-default-*.js"))[0]
src = open(LD, encoding="utf-8").read()

# Find every "{vendorId:NNN,productId:NNN,...}" object and slice out a window
# large enough to contain its scalar fields.
models = {}
for m in re.finditer(r"\{vendorId:(\d+),productId:(\d+)", src):
    start = m.start()
    window = src[start:start + 400]

    def field(key, default=None):
        mm = re.search(rf'{key}:"([^"]*)"', window)
        return mm.group(1) if mm else default

    vid = int(m.group(1))
    pid = int(m.group(2))
    name = field("name")
    if not name:
        continue
    connect = field("connectType", "USB")
    supplier = field("supplierName", "ajazz")
    kb_img = field("keyboardImg")
    routes_m = re.search(r"routesName:\[([^\]]*)\]", window)
    routes = re.findall(r'"([^"]+)"', routes_m.group(1)) if routes_m else []

    key = (vid, pid, name, connect)
    # de-dupe identical (vid,pid,name,connect) tuples; keep the richest routesName
    if key not in models or len(routes) > len(models[key]["routesName"]):
        models[key] = {
            "vendorId": vid,
            "productId": pid,
            "name": name,
            "supplierName": supplier,
            "connectType": connect,
            "routesName": routes,
            "keyboardImg": kb_img,
        }

# Drop generic placeholder names that aren't real models.
GENERIC = {
    "USB Keyboard", "Gaming Keyboard", "AJAZZ KEYBOARD", "Keyboard", "Default",
    "2.4G Dongle", "HS USB Dongle", "AJAZZ Keyboard", "gW997mgkb",
}
rows = [v for v in models.values() if v["name"] not in GENERIC]
rows.sort(key=lambda r: (r["name"], r["productId"], r["connectType"]))

body = json.dumps(rows, ensure_ascii=False, indent=2)
ts = f"""// AUTO-GENERATED by extract_models.py from {LD.split('/')[-1]}.
// Do not hand-edit; re-run the extractor after an upstream rebuild.

export interface KeyboardModel {{
  vendorId: number;
  productId: number;
  name: string;
  supplierName: string;
  /** "USB" | "2.4G" | ... — transport this entry describes. */
  connectType: string;
  /** UI feature areas this model exposes (customKeys, lighting, macro, performance, advancedKeys, settings, ...). */
  routesName: string[];
  /** Keyboard render image filename under cache/static/keyboards/ (may be null). */
  keyboardImg: string | null;
}}

export const KEYBOARD_MODELS: KeyboardModel[] = {body};

/** Look up a model by USB vendor/product id (first match). */
export function findModel(vendorId: number, productId: number): KeyboardModel | undefined {{
  return KEYBOARD_MODELS.find((m) => m.vendorId === vendorId && m.productId === productId);
}}
"""
open("src/protocol/models.ts", "w", encoding="utf-8").write(ts)
print(f"Wrote {len(rows)} models to src/protocol/models.ts")
print("Sample:", ", ".join(sorted({r["name"] for r in rows})[:12]))
